version: "3.9"
services:
  nextchat:
    container_name: nextchat
    image: yidadaa/chatgpt-next-web
    ports:
      - "0.0.0.0:3000:3000"  # This allows external access
    environment:
      - DEEPSEEK_API_KEY=sk-cf56f2572c704a70ad2e6792ad54f344
      - DEEPSEEK_URL=https://api.deepseek.com
      - CODE=your_secure_password_here
    restart: unless-stopped
